# Generated by Django 5.0.5 on 2024-06-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="password",
            field=models.CharField(max_length=256),
        ),
    ]
