# Generated by Django 5.0.5 on 2024-06-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_save",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("travel_company", models.TextField()),
                ("area", models.TextField()),
                ("title", models.TextField()),
                ("price", models.IntegerField(null=True)),
                ("date", models.TextField()),
                ("departure_city", models.TextField()),
                ("duration", models.IntegerField(null=True)),
                ("remaining_quota", models.TextField()),
                ("tour_schedule", models.TextField()),
                ("url", models.TextField()),
            ],
            options={
                "db_table": "User_save",
            },
        ),
        migrations.DeleteModel(
            name="Lion",
        ),
        migrations.DeleteModel(
            name="Lion_save",
        ),
    ]
